#! /bin/bash

CATALINA_HOME=/usr/local/tomcat7
WEB_ROOT=$CATALINA_HOME/webapps/web-3.0
CDN=""
DEVELOP_PATH=`pwd`
PROJECT_NAME="ipc-web-front-end"

init(){
	curl --silent --location https://rpm.nodesource.com/setup | bash -
	sudo yum -y install nodejs
	npm install -g fis3
	npm install -g fis3-postpackager-loader
}

stop(){
	:
}

update(){
	:
}

config(){

	rm -rf $WEB_ROOT/$PROJECT_NAME $WEB_ROOT/*.html
	export CDN_PATH=$CDN

	fis3 release $1 -d $WEB_ROOT
	
	rm -rf $WEB_ROOT/deploy
}

start(){
	:
}

case "$1" in
	
	init)
		init
		;;
	stop)
		stop
		;;
	update)
		update
		;;
	config)
		config $2 $3
		;;
	start)
		start
		;;
	help|*)
	echo $"Usage: $0 {init|stop|update|config|start}"
	exit 1
	;;

esac

exit 0