#! /bin/bash

CATALINA_HOME=/usr/local/tomcat7
WEB_ROOT=$CATALINA_HOME/webapps/web-3.0
CDN_PATH="http://cdn.tplinkcloud.com/"
DEVELOP_PATH=`pwd`


init(){
	curl --silent --location https://rpm.nodesource.com/setup | bash -
	sudo yum -y install nodejs
	npm install -g fis3
}

stop(){
	:
}

update(){
	:
}

config(){

	rm -rf $WEB_ROOT/common $WEB_ROOT/components $WEB_ROOT/data $WEB_ROOT/views $WEB_ROOT/index.html

	sed -i "s@PRODUCT_CDN_PATH\s*=\s*'[^']*'@PRODUCT_CDN_PATH = '$CDN_PATH'@g" $DEVELOP_PATH/fis-conf.js

	fis3 release $1 -d $WEB_ROOT
	
	if [ "$1"x = "product"x ] ; then
		find $WEB_ROOT -maxdepth 2 -type d -not -name pages -not -name "." -exec rm -ir {} \;
	fi
	rm -rf $WEB_ROOT/deploy $WEB_ROOT/fis-conf.js

	
	
}

start(){
	:
}

case "$1" in
	
	init)
		init
		;;
	stop)
		stop
		;;
	update)
		update
		;;
	config)
		config $2 $3
		;;
	start)
		start
		;;
	help|*)
	echo $"Usage: $0 {init|stop|update|config|start}"
	exit 1
	;;

esac

exit 0